[tools]
bat = 'latest'
delta = 'latest'
difftastic = { version = 'latest', exe = 'difft' }
eza = 'latest'
ghq = "latest"
go = "latest"
neovim = 'latest'
node = 'latest'
ripgrep = 'latest'
tmux = 'latest'
yarn = 'latest'
